coordinates:
  name: Microsoft.ApplicationInsights
  provider: nuget
  type: nuget
revisions:
  2.10.0-beta4:
    described:
      facets:
        data:
          - test
    licensed:
      declared: MIT-0
  2.13.1:
    described:
      facets:
        data:
          - test
    licensed:
      declared: MIT-0
